#!/bin/sh

# Exit on first error
set -e

# Update app directory
PROJECT_ROOT=/var/www/app
git --work-tree=$PROJECT_ROOT --git-dir=$PROJECT_ROOT.git checkout -f

# Install new dependencies
cd $PROJECT_ROOT
npm install

# Restart application
${PROJECT_ROOT}/node_modules/.bin/pm2 restart ${PROJECT_ROOT}/bin/www
